// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHi4yV45ZMgSsnCi7mA2R9AslnbzzM_8',
    appId: '1:181951791910:web:f813e719b380d6c8fd77e7',
    messagingSenderId: '181951791910',
    projectId: 'ifalcontrace-67bf9',
    authDomain: 'ifalcontrace-67bf9.firebaseapp.com',
    storageBucket: 'ifalcontrace-67bf9.firebasestorage.app',
    measurementId: 'G-5BPYDMBF4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHfjHwCUkV1MplJy0aaDN1kjNpeQash8',
    appId: '1:181951791910:android:df48ef0d40fe6e8efd77e7',
    messagingSenderId: '181951791910',
    projectId: 'ifalcontrace-67bf9',
    storageBucket: 'ifalcontrace-67bf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2w8viMSy9o592GG3wQOstn0UQLCbYXI',
    appId: '1:181951791910:ios:b0d4a3391679654cfd77e7',
    messagingSenderId: '181951791910',
    projectId: 'ifalcontrace-67bf9',
    storageBucket: 'ifalcontrace-67bf9.firebasestorage.app',
    iosBundleId: 'com.lumko.ifalcontrace',
  );
}
